[general]
timezone = "Europe/Berlin"

[google]
# 1) Paste your GOOGLE SERVICE ACCOUNT JSON between the triple quotes exactly as received
service_account_json = """
{
  "type": "service_account",
  "project_id": "YOUR_PROJECT",
  "private_key_id": "XXXX",
  "private_key": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n",
  "client_email": "your-sa@your-project.iam.gserviceaccount.com",
  "client_id": "1234567890",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth"
}
"""

# 2) After you create them below, fill in:
drive_top_folder_id = "YOUR_DRIVE_FOLDER_ID"
sheet_id = "YOUR_SHEET_ID"
